import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{ArrowUpRight,Menu,X,Play,Quote}from'lucide-react';import'./styles.css';
const cats=['Business & Leadership','Social Impact','Arts & Culture','Technology & Innovation','Education','Healthcare','Public Service','Unsung Heroes'];
const jury=[['Jaikrishna B. (J.K.)','President & Group CHRO','Amara Raja Group','https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=700&q=80'],['Rajesh Dhuddu','Blockchain & Cybersecurity Leader','PwC','https://images.unsplash.com/photo-1566492031773-4f4e44671d66?auto=format&fit=crop&w=700&q=80'],['Pratyusha Sharma','HR Head','Invesco','https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=700&q=80'],['Meraj Faheem','CEO','Telangana Innovation Cell','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=80'],['Debashish Ghosh','Entrepreneur','Independent','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=80']];
function App(){const[menu,setMenu]=useState(false),[modal,setModal]=useState(false),[video,setVideo]=useState(false),[scrolled,setScrolled]=useState(false);useEffect(()=>{const f=()=>setScrolled(scrollY>40);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);const go=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};return <div className="app">
<header className={scrolled?'header scrolled':'header'}><div className="brand" onClick={()=>go('home')}><span>H</span><div>HEROES<small>OF HYDERABAD</small></div></div><nav>{['about','categories','jury','gallery'].map((x,i)=><button key={x} onClick={()=>go(x)}>{['About','Categories','Jury','Gallery'][i]}</button>)}</nav><button className="navCta" onClick={()=>setModal(true)}>NOMINATE <ArrowUpRight size={15}/></button><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
{menu&&<div className="mobileNav">{['about','categories','jury','gallery'].map((x,i)=><button key={x} onClick={()=>go(x)}>{['About','Categories','Jury','Gallery'][i]}</button>)}<button onClick={()=>setModal(true)}>Nominate a Hero</button></div>}
<section id="home" className="hero"><div className="heroBg"/><div className="grain"/><div className="heroCopy"><p className="eyebrow">TRIUMPHS OF TALENT PRESENTS</p><h1>HEROES<br/><i>OF</i> HYDERABAD</h1><p className="heroText">Celebrating the dreamers, doers and disruptors who make our city unstoppable.</p><div className="heroActions"><button className="goldBtn" onClick={()=>setModal(true)}>NOMINATE A HERO <ArrowUpRight/></button><button className="playBtn" onClick={()=>setVideo(true)}><span><Play size={15} fill="currentColor"/></span> WATCH THE STORY</button></div></div><div className="heroMeta"><span>2025 EDITION</span><span>HYDERABAD · INDIA</span></div><div className="scroll">SCROLL TO DISCOVER ↓</div></section>
<section id="about" className="manifesto section"><div className="sectionTag">01 / THE IDEA</div><div><h2>A CITY IS ONLY<br/><em>AS GREAT</em> AS ITS PEOPLE.</h2><p>Hyderabad is built on stories of courage, conviction and quiet impact. Heroes of Hyderabad exists to bring those stories into the light — not popularity, but purpose; not noise, but meaningful contribution.</p><button className="textBtn" onClick={()=>setModal(true)}>NOMINATIONS ARE OPEN <ArrowUpRight/></button></div></section>
<section id="categories" className="categories section"><div className="sectionHead"><div className="sectionTag">02 / CATEGORIES</div><h2>EVERY HERO<br/><em>HAS A STORY.</em></h2></div><div className="catGrid">{cats.map((c,i)=><div className="cat" key={c}><span>0{i+1}</span><h3>{c}</h3><ArrowUpRight/></div>)}</div></section>
<section className="statement"><div className="statementImage"/><div className="statementText"><p className="eyebrow">THE HEART OF HYDERABAD</p><h2>REAL IMPACT.<br/><em>REAL PEOPLE.</em></h2><p>From boardrooms to neighbourhoods, laboratories to classrooms, the city is moved forward by people who choose to act.</p></div></section>
<section id="jury" className="jury section"><div className="sectionHead"><div className="sectionTag">03 / THE JURY</div><h2>PEOPLE WHO<br/><em>KNOW IMPACT.</em></h2></div><div className="juryGrid">{jury.map(([n,r,o,img])=><article className="juryCard" key={n}><div className="portrait"><img src={img}/><div className="portraitNum">HOH / 25</div></div><h3>{n}</h3><p>{r}</p><small>{o}</small></article>)}</div></section>
<section className="quote"><Quote size={42}/><blockquote>“Heroes of Hyderabad is our city's story told through its people.”</blockquote><p>— MOHAMED FAYAZ, FOUNDER · TRIUMPHS OF TALENT</p></section>
<section id="gallery" className="gallery section"><div className="sectionHead"><div className="sectionTag">04 / THE MOMENTS</div><h2>THE NIGHT<br/><em>WE CELEBRATED.</em></h2></div><div className="galleryGrid"><div className="g g1"/><div className="g g2"/><div className="g g3"/><div className="g g4"/><div className="g g5"/></div></section>
<section className="finalCta"><div className="finalBg"/><p className="eyebrow">KNOW A HERO?</p><h2>PUT THEIR<br/><em>STORY ON STAGE.</em></h2><button className="goldBtn" onClick={()=>setModal(true)}>START A NOMINATION <ArrowUpRight/></button></section>
<footer><div className="footerBrand">HEROES<br/><em>OF HYDERABAD</em></div><div><p>AN INITIATIVE BY</p><strong>TRIUMPHS OF TALENT</strong></div><div className="footLinks"><button onClick={()=>go('about')}>About</button><button onClick={()=>go('jury')}>Jury</button><button onClick={()=>setModal(true)}>Nominate</button></div><div className="copyright">© 2026 Triumphs of Talent. All rights reserved.</div></footer>
{modal&&<div className="overlay" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}><X/></button><p className="eyebrow">HEROES OF HYDERABAD</p><h2>NOMINATE A <em>HERO.</em></h2><p className="modalIntro">Tell us about someone whose work, courage or contribution makes Hyderabad better.</p><form onSubmit={e=>{e.preventDefault();setModal(false);alert('Thank you! Your nomination has been recorded.')}}><input placeholder="Your name" required/><input placeholder="Email address" type="email" required/><input placeholder="Nominee name" required/><input placeholder="Organisation / designation"/><select defaultValue=""><option value="" disabled>Select category</option>{cats.map(c=><option key={c}>{c}</option>)}</select><textarea placeholder="Why should this person be recognised?" rows="4" required/><button className="goldBtn" type="submit">SUBMIT NOMINATION <ArrowUpRight/></button></form></div></div>}
{video&&<div className="overlay" onClick={()=>setVideo(false)}><div className="videoBox" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setVideo(false)}><X/></button><div className="videoPlaceholder"><Play size={55} fill="currentColor"/><p>Heroes of Hyderabad · 2025</p></div></div></div>}</div>};createRoot(document.getElementById('root')).render(<App/>);