import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{ArrowUpRight,Menu,X,Play,Quote,ChevronDown}from'lucide-react';import'./styles.css';
const cats=['Inspirational Heroes','Heroes of HR','Social Impact','Arts & Culture','Technology & Innovation','Education & Academia','Philanthropy','Sustainability','Healthcare','Business & Leadership','Public Service','Young Achievers','Unsung Heroes'];
const jury=[['Jaikrishna B. (J.K.)','President & Group CHRO','Amara Raja Group','https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=900&q=85'],['Rajesh Dhuddu','Blockchain & Cybersecurity Leader','PwC India','https://images.unsplash.com/photo-1566492031773-4f4e44671d66?auto=format&fit=crop&w=900&q=85'],['Pratyusha Sharma','HR Head','Invesco','https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=900&q=85'],['Meraj Faheem','CEO','Telangana Innovation Cell','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85'],['Debashish Ghosh','Entrepreneur','Independent','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85']];
const video='https://www.youtube.com/embed/HXwT8EF0pio?autoplay=1&mute=1&controls=0&loop=1&playlist=HXwT8EF0pio&modestbranding=1&playsinline=1&rel=0';
function App(){const[menu,setMenu]=useState(false),[modal,setModal]=useState(false),[videoOpen,setVideoOpen]=useState(false),[scrolled,setScrolled]=useState(false);useEffect(()=>{const f=()=>setScrolled(scrollY>45);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);const go=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};return <div className="app">
<header className={scrolled?'header scrolled':'header'}><button className="brand" onClick={()=>go('home')}><span className="brandMark">ho</span><span className="brandWord">HEROES <b>OF HYDERABAD</b></span></button><nav>{[['about','THE STORY'],['categories','CATEGORIES'],['jury','THE JURY'],['gallery','MOMENTS']].map(([x,l])=><button key={x} onClick={()=>go(x)}>{l}</button>)}</nav><button className="navCta" onClick={()=>setModal(true)}>NOMINATE <ArrowUpRight size={14}/></button><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
{menu&&<div className="mobileNav">{[['about','The Story'],['categories','Categories'],['jury','The Jury'],['gallery','Moments']].map(([x,l])=><button key={x} onClick={()=>go(x)}>{l}</button>)}<button onClick={()=>setModal(true)}>Nominate a Hero</button></div>}
<section id="home" className="hero"><div className="heroVideo"><iframe title="Hyderabad cinematic background" src={video} allow="autoplay; encrypted-media; picture-in-picture"/></div><div className="heroVeil"/><div className="heroGlow"/><div className="heroCenter"><p className="kicker">TRIUMPHS OF TALENT PRESENTS</p><div className="logoLockup"><span>ho</span><span className="charminarGlyph">⌂</span><span>yd</span></div><h1>HEROES <i>OF</i> HYDERABAD</h1><p className="heroLine">The city has many faces. Its heroes are the ones who leave a mark.</p><div className="heroActions"><button className="blueBtn" onClick={()=>setModal(true)}>NOMINATE A HERO <ArrowUpRight/></button><button className="storyBtn" onClick={()=>setVideoOpen(true)}><span><Play size={13} fill="currentColor"/></span> WATCH THE STORY</button></div></div><div className="heroBottom"><span>HYDERABAD · TELANGANA · INDIA</span><span>JURY-DRIVEN RECOGNITION</span></div><button className="discover" onClick={()=>go('about')}>DISCOVER <ChevronDown size={14}/></button></section>
<section id="about" className="story section"><div className="sectionIndex">01<br/><span>THE STORY</span></div><div className="storyContent"><p className="eyebrow">NOT FAME. IMPACT.</p><h2>HYDERABAD'S<br/><em>STORY</em> IS ITS PEOPLE.</h2><p className="lead">Heroes of Hyderabad is a jury-driven platform celebrating the people whose work, courage and contribution make this city stronger.</p><div className="storyGrid"><div><strong>75+</strong><span>ACHIEVERS<br/>CELEBRATED</span></div><div><strong>13</strong><span>CATEGORIES<br/>OF IMPACT</span></div><div><strong>01</strong><span>CITY.<br/>MANY STORIES.</span></div></div><button className="lineBtn" onClick={()=>setModal(true)}>NOMINATIONS ARE OPEN <ArrowUpRight/></button></div></section>
<section className="heritage"><div className="heritageImage"/><div className="heritageCopy"><p className="eyebrow">THE SOUL OF THE CITY</p><h2>FROM THE<br/><em>CHARMINAR</em><br/>TO THE CITY'S FUTURE.</h2><p>Old City streets. New ideas. Quiet acts of courage. Hyderabad's character lives in people who build, serve, create and keep moving forward.</p><div className="heritageRule"/></div></section>
<section id="categories" className="categories section"><div className="sectionIndex">02<br/><span>CATEGORIES</span></div><div className="categoryContent"><p className="eyebrow">RECOGNITION WITHOUT NOISE</p><h2>EVERY FIELD.<br/><em>ONE STANDARD.</em></h2><div className="catGrid">{cats.map((c,i)=><div className="cat" key={c}><span>{String(i+1).padStart(2,'0')}</span><h3>{c}</h3><ArrowUpRight size={17}/></div>)}</div></div></section>
<section className="principles"><div><span className="principleNo">01</span><h3>MERIT FIRST</h3><p>Recognition is earned through contribution, not popularity.</p></div><div><span className="principleNo">02</span><h3>JURY DRIVEN</h3><p>An independent panel evaluates the stories and impact.</p></div><div><span className="principleNo">03</span><h3>NO PAY-TO-WIN</h3><p>A platform built around credibility, not nomination fees.</p></div></section>
<section id="jury" className="jury section"><div className="sectionIndex">03<br/><span>THE JURY</span></div><div className="juryContent"><p className="eyebrow">THE PEOPLE BEHIND THE CHOICE</p><h2>EXPERIENCE<br/><em>MEETS INTEGRITY.</em></h2><div className="juryGrid">{jury.map(([n,r,o,img])=><article className="juryCard" key={n}><div className="portrait"><img src={img} alt={n}/><span>HOH / 25</span></div><h3>{n}</h3><p>{r}</p><small>{o}</small></article>)}</div></div></section>
<section className="quote"><Quote size={38}/><blockquote>“Heroes of Hyderabad is not just an awards night — it is the story of our city, told through its people.”</blockquote><p>MOHAMMED FAYAZ · FOUNDER, TRIUMPHS OF TALENT</p></section>
<section id="gallery" className="gallery section"><div className="sectionIndex">04<br/><span>MOMENTS</span></div><div className="galleryContent"><p className="eyebrow">THE NIGHT WE CELEBRATED</p><h2>STORIES THAT<br/><em>DESERVE A STAGE.</em></h2><div className="galleryGrid"><div className="g g1"/><div className="g g2"/><div className="g g3"/><div className="g g4"/><div className="g g5"/></div></div></section>
<section className="finalCta"><p className="eyebrow">KNOW SOMEONE WHO MATTERS?</p><h2>GIVE THEIR<br/><em>STORY A STAGE.</em></h2><p>Nominate a dreamer, doer or disruptor who makes Hyderabad better.</p><button className="blueBtn" onClick={()=>setModal(true)}>START A NOMINATION <ArrowUpRight/></button></section>
<footer><div className="footerLogo"><div className="footerHo">ho <span>⌂</span> yd</div><small>HEROES OF HYDERABAD</small><p>AN INITIATIVE BY<br/><b>TRIUMPHS OF TALENT</b></p></div><div className="footLinks"><button onClick={()=>go('about')}>The Story</button><button onClick={()=>go('categories')}>Categories</button><button onClick={()=>go('jury')}>The Jury</button><button onClick={()=>setModal(true)}>Nominate</button></div><div className="footerMeta">HYDERABAD · INDIA<br/><span>© 2026 TRIUMPHS OF TALENT</span></div></footer>
{modal&&<div className="overlay" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}><X/></button><p className="eyebrow">HEROES OF HYDERABAD</p><h2>NOMINATE A<br/><em>HERO.</em></h2><p>Tell us about a person whose work, courage or contribution deserves recognition.</p><form onSubmit={e=>{e.preventDefault();setModal(false);alert('Thank you! Your nomination has been recorded.')}}><input placeholder="Your name" required/><input placeholder="Email address" type="email" required/><input placeholder="Nominee name" required/><input placeholder="Organisation / designation"/><select defaultValue=""><option value="" disabled>Select category</option>{cats.map(c=><option key={c}>{c}</option>)}</select><textarea placeholder="Why should this person be recognised?" rows="5" required/><button className="blueBtn" type="submit">SUBMIT NOMINATION <ArrowUpRight/></button></form></div></div>}
{videoOpen&&<div className="overlay" onClick={()=>setVideoOpen(false)}><div className="videoModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setVideoOpen(false)}><X/></button><iframe title="Heroes of Hyderabad story" src={video.replace('autoplay=1','autoplay=1')} allow="autoplay; encrypted-media; picture-in-picture"/></div></div>}</div>};createRoot(document.getElementById('root')).render(<App/>);